### PR TITLE
Development dorien

### PR DESCRIPTION
**Pull request by dorienmc**
Update formide tools.
Adds new tests, testing of invalid parameters, updating over override parameters and more.

### CODE REVIEW

**Comment by ChrisTerBeke** [comment]
Test fails. Forgot to add a file?

**Comment by dorienmc** [comment]
Tests now pass, there were indeed some capital-sensitive issues.
Do we also need a pull request from dev to master to test this on the platform-dev website?

**Comment by ChrisTerBeke** [comment]
We need to make a release to get it on platform-dev, dev works just like production when it comes to package dependencies.

**Comment by dorienmc** [comment]
So `platform.formide.com` is using the `master` branch and `platform-dev.formide.com` is using the `development` branch? And to use the updated `formide-tools` (on `platform-dev`) I have to run the `release` file in the root of the repo? And after that if we want to use it on `platform.formide`? Make a pull request and/or run the `release` file, .... something else?

**Pull request merged**
